### ISSUE TITLE
Invalid io_group when running full ndlar sim

### ISSUE THREAD

**Issue by AlexWilkinsonnn** [DUNE/larnd-sim#87]
When running simulate_pixels with the config
```
python ./simulate_pixels.py --input_filename=../data/edep_h5/0m/00/FHC.1000000.edep.h5 --detector_properties=../larndsim/detector_properties/ndlar-module.yaml --pixel_layout=../larndsim/pixel_layouts/multi_tile_layout-3.0.40.yaml --output_filename=../data/detsim/FHC.1000000.larnd-sim.h5 --response_file=../larndsim/bin/response_38.npy
```
I get the following error after processing a few events
```
Traceback (most recent call last):                                              
  File "./simulate_pixels.py", line 571, in <module>
    fire.Fire(run_simulation)
  File "/home/awilkinson/.local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/awilkinson/.local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/awilkinson/.local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./simulate_pixels.py", line 518, in run_simulation
    fee.export_to_hdf5(event_id_list_batch,
  File "/unix/dune/awilkinson/extrapolation/larnd-sim/cli/../larndsim/fee.py", line 154, in export_to_hdf5
    packets[-1].chip_key = Key(io_group,0,0)
  File "/unix/dune2/awilkinson/miniconda3/envs/larnd-sim/lib/python3.8/site-packages/larpix/key.py", line 44, in __init__
    self.io_group = args[0]
  File "/unix/dune2/awilkinson/miniconda3/envs/larnd-sim/lib/python3.8/site-packages/larpix/key.py", line 161, in io_group
    raise ValueError('io_group must be 1-byte ({} invalid)'.format(io_group))
ValueError: io_group must be 1-byte (256 invalid)
```
I think this bug is caused by commit b820ae8476aa4abf812720d1544a8f4475f24f14 with the introduction of the `MODULE_TO_IO_GROUPS` property. If I go back to tag `v0.3.2` before this commit I do not get this error.

I am not confident enough with this hierarchy to apply the correct fix myself.

Alex

**Comment by soleti** [comment]
Hi @AlexWilkinsonnn I think this bug was fixed yesterday, could you try by pulling the latest commit?

**Comment by AlexWilkinsonnn** [comment]
Hello, yes you're right it works now. I had this issue yesterday and didn't check for any new commits today.
